### ISSUE TITLE
There is not a method to send a handled exception to HockeyApp

### ISSUE THREAD

**Issue by vhugogarcia** [bitstadium/HockeySDK-Xamarin#27] opened 2016-06-08 16:05 UTC
Hello friends,

We are currently working in a project in Xamarin and we are consuming for example the web services from the PCL project, however we could not find a method or library to help us to send to HockeyApp manually the exception.

Basically what we would like to do is:
try
{
.... 
}
catch(Exception ex)
{
    // Send to HockeyApp the handled exception from PCL project.
}

Is there a way to do that, somehow? 

As a matter of workaround we created a log file on each platform when handled exceptions, and we would like also to find a way to send those log files to HockeyApp if not possible from PCL then from platform specific, is there a way to do that?

Thanks in advance

**Comment by lumaxis** [comment] 2016-06-08 16:18
Hi @vhugogarcia!
HockeyApp currently does not support handled exceptions, neither in the SDKs nor on the backend/dashboard. This is something we have very high on our todo list though and want to have in the future.

**Comment by vhugogarcia** [comment] 2016-06-08 16:28
Thanks @lumaxis for your quick answer. However I found there is a way to send specific log files into HockeyApp.

https://support.hockeyapp.net/kb/client-integration-ios-mac-os-x-tvos/how-to-add-application-specific-log-data-on-ios-or-os-x

However on Xamarin that is missing somehow?

Is that for a different purpose?

**Comment by lumaxis** [comment] 2016-06-08 16:30
That functionality is aimed at enriching crash logs of unhandled exceptions with for example application logs.

**Comment by lumaxis** [comment] 2016-06-08 19:08
To answer the other part of your question: Yes, this functionality is also available in the Xamarin SDK

**Comment by huskywhale** [comment] 2016-08-04 14:34
any progress on this ?

**Comment by TroubleMakerBen** [comment] 2016-08-04 15:16
Hi @huskywhale,
We have this on our backlog but I can't provide you with an ETA for tracking handled exceptions.

**Comment by markmadlangbayan** [comment] 2016-08-04 15:36
1+

**Comment by huskywhale** [comment] 2016-08-08 16:32
To people who want to try a workaround. Use web-hooks
https://support.hockeyapp.net/kb/third-party-bug-trackers-services-and-webhooks/how-to-use-hockeyapp-webhooks

**Comment by ranterle** [comment] 2016-09-15 13:19
Closing this issue for now - we are tracking this and will let everybody know once we have something to report on.

**Comment by logikonline** [comment] 2016-10-07 18:34
this is beyond important for realistic use of this error reporting in Xamarin.

**Comment by ChaseFlorell** [comment] 2016-11-24 19:51
This issue alone is preventing me from switching to HA.

**Comment by ranterle** [comment] 2016-11-25 08:15
Thanks for all the feedback here, and definitely keep it coming. Here, in our [support forum](https://support.hockeyapp.net) and our public Slack channel: https://slack.hockeyapp.net
We appreciate you telling us what you need and this is high up on our list. However, handled exceptions are different to app crashes in many ways and thus require broader changes than just to the SDK.
Please also note the recent changes announced at the [Connect (); event](https://www.hockeyapp.net/blog/2016/11/16/mobile-center-next-generation-hockeyapp.html) which also aims to deliver on handled exceptions.

**Comment by callanh** [comment] 2017-05-11 08:20
I think I agree that HockeyApp should support sending caught exceptions.  My main concern is how do I get the full stack trace with line numbers for exceptions in my Xamarin iOS and Android apps?  There many types of exception that do not warrant a hard crash of the app.  I can easily catch and log these myself but not having the line numbers makes issues much harder to diagnose.

**Comment by TroubleMakerBen** [comment] 2017-05-12 07:09
Hey @callanh,
not being able to get line numbers is currently a limitation of the Xamarin runtime. Honestly, we'd love to do something about it.
We are hard at work [on Mobile Center](https://www.hockeyapp.net/mobile-center/about/) right now and want to make the overall experience better, and line numbers for exceptions and support for handled exceptions is definitely on our backlog.

I'm reopening this issue for better visibility.

**Comment by svedmark** [comment] 2017-05-12 13:14
+1 on this! Currently transitioning from Xamarin Insights...  @huskywhale, did you try using the API from a Xamarin app; and if so, how did HA manage to display the stack trace that was posted?

**Comment by TroubleMakerBen** [comment] 2017-05-12 15:03
@svedmark we had line numbers in HA until one of last year's Xamarin releases.

Iterating this again to make it clear: we know this is something esp. Xamarin devs want and need. It's very high up on our list of priorities. We want to get it right, though, especially in a cross-platform context, and for that, we have to take a step back and think how "handled exceptions" can be used and will be used in other platforms in a meaningful way, that can scale well, etc. etc.
We are getting there.

That said, I'm super interested in how you guys use handled exceptions:
* which errors you track with them?
* what other info besides a stack trace is needed?
* if your app has a large install base, is volume a problem for you?
* ...

I'd love to get in touch with you, via email, or better, through skype in a quick call. Please shoot me an email to "bereimol" at "my imployer from redmond" dot com."

**Comment by michelmoorlag** [comment] 2017-05-18 14:22
I am developing a Xamarin Forms application and sometimes my app crashes at startup. I don't handle them because I can see the error and stacktrace in the hockeyapp dashboard which give me very important information to fix it. 
I would prefer to handle the exception though, show an error to the user and send the handled exception to hockeyapp through the sdk. What I am mostly interested in is the message and the XF stacktrace.

**Comment by EmilAlipiev** [comment] 2017-06-17 14:13
@TroubleMakerBen Simple answer anything we want to catch inside try catch in forms project. what are we supposed to do when a crash occurs in forms project and we use try catch, should we leave catch part empty and let nothing to be caught? hockeyapp is totally useless without this.  similar like xamarin insights how we were able to catch using report action.

**Comment by TroubleMakerBen** [comment] 2017-06-19 23:45
Hey @EmilAlipiev,
I understand your frustration and we are working hard on [Mobile Center](https://www.hockeyapp.net/mobile-center/about/) to bring you a solution that brings the function that Xamarin Insights had.
For now, maybe you can utilize the Metrics feature to send custom events for your handled error cases?

I really hope you have some patience with us.
Best,
Benny

**Comment by ndastur** [comment] 2017-06-30 19:16
+1 for this too.
All the code for sending a stack trace etc is there. Is it not a case of exposing a method to just capture and send that

**Comment by TroubleMakerBen** [comment] 2017-07-03 17:43
@ndastur 
I see where you are coming from and, yes, we could expose this easily. We need to think about this API in 
a) a cross platform context
b) a scaling context

believe me, it's not as easy as exposing an api in an SDK.
We're iterating on Mobile Center really fast, please bear with us. =)

**Comment by less0** [comment] 2017-07-17 09:31
> That said, I'm super interested in how you guys use handled exceptions:
>
> * which errors you track with them?
> * what other info besides a stack trace is needed?

I have been dealing with occasional connection issues, which I'd like to log with HockeyApp for further insights. I did know where they occurred, but I have not been able to trace them down to the root cause. The app was tested with the customer (not the future users) and we could not afford to let the app crash every time, just to log the exception. 

Stack trace would be quite fine, inner exceptions even more.

**Comment by ndastur** [comment] 2017-07-17 16:26
@TroubleMakerBen as @less0 says it is about being about to track errors with a stack trace without allowing the app to crash. There are non-fatal exceptions and the user experience can be managed better than just crashing.

**Comment by EmilAlipiev** [comment] 2017-07-18 10:23
I was told that in mean time I can report exception as EVENT but how can I see the details of an event. I can only see the name of the event in the dashboard.

**Comment by TroubleMakerBen** [comment] 2017-07-18 19:09
@ndastur @less0 I completely understand the use-case. Like I said, we're taking these requests very seriously. Please bear with us. Mobile Center will get them eventually.

@EmilAlipiev about the workaround. You are right, we are not surfacing the custom properties in the HockeyApp portal. To see them, you need to link HockeyApp to Application Insights as described in our [Knowledge Base](https://support.hockeyapp.net/kb/general-account-management-2/custom-events-with-application-insights).

We get that this all is just a workaround and this needs to be more comfortable. We are well aware and work as hard as we can, believe me. We hear you!

**Comment by ChaseFlorell** [comment] 2017-07-18 20:52
> That said, I'm super interested in how you guys use handled exceptions:
>    - which errors you track with them?

The use case I have is that we have a method that we use to run all Commands that talk to external resources.

```
    await RunSafe(MyVolitileTask, OnError);
```

```
public Task MyVolitileTask() {
    throw new Exception("I Broke");
}

public void OnError() {
    // capture exception and log to HockeyApp
    // toast a message to the user
}
```

The RunSafe method wraps the `MyVolitileTask` in a Try/Catch and the catch calls OnError.

Essentially, this gives us the ability to see errors in our insights but keep the app alive.

**Comment by EmilAlipiev** [comment] 2017-07-18 22:12
@TroubleMakerBen I have successfully created bridge between AI and hockeyapp. it actually works but although I am sending event as below. I am not able to see "properties" anywhere in AI. Where do I see properties?

  HockeyApp.MetricsManager.TrackEvent(eventName: name, properties: properties, measurements: new Dictionary<string, double> { { "time", TimeSpent } });

**Comment by drewlederman** [comment] 2017-11-04 23:00
How did this go from "very high" on the todo list to wontfix?

**Comment by logikonline** [comment] 2017-11-04 23:32
It is beyond insane that a simple method cannot be added to log an error.  It is perhaps the single most important method of reporting errors for Xamarin Forms.  Clearly no one at Hockey uses Xamarin Forms.

**Comment by ndastur** [comment] 2017-11-05 16:25
Forget using xamarin forms. It suggests the lack of using any software. But the cynic in me say now it's been bought by MS they realise it is a must have and so will form part of a premium feature only.

**Comment by TroubleMakerBen** [comment] 2017-11-06 18:20
Hey everyone,

Let me explain what happens over here. I'm to blame to not put another info in here about why I added the #wontfix here. 

As I wrote above:
> We are hard at work on Mobile Center right now and want to make the overall experience better, and line numbers for exceptions and support for handled exceptions is definitely on our backlog.

We are currently working on [Mobile Center](https://www.hockeyapp.net/mobile-center/about/) which is the next generation of HockeyApp. It does not come with support for handled exceptions just yet, but it's gonna happen – because of your input here and elsewhere, so keep the feedback coming.
Please bear with us, we really value your input and patience. Please feel free to reach out to me via mail (bereimol at microsoft dot com) or [HockeyCamp](https://hockeycamp.slack.com/).

Benjamin

**Comment by nmilcoff** [comment] 2017-11-06 20:16
It has been longer than a year and the feature keeps being delayed in time... Most of us have been using the already deprecated Xamarin.Insights for even longer than that and can't really move out unless we have a platform with at least the same feature set. 

I don't want to be mean, but please, PLEASE make this happen.

**Comment by ndastur** [comment] 2017-11-07 13:42
Because this is a forced migration it is causing so much trouble. The original feature was an essential. At the very least cpuld the string limit of 40 characters on events be lifted? It would be a quick fix and also show some goodwill to your users.

**Comment by TroubleMakerBen** [comment] 2017-11-07 17:50
I just talked to my PM and we're currently looking at an ETA in Spring 2018 for this in Mobile Center.

**Comment by callanh** [comment] 2017-11-07 23:01
> We are hard at work on Mobile Center right now and want to make the overall experience better, and line numbers for exceptions and support for handled exceptions is definitely on our backlog.

Just to clarify are you talking about both handled exceptions and line number in stack traces for the ETA of Spring 2018? If so then it's a massive improvement for the Xamarin stack! If it is only handled exceptions then it's an improvement but not a game changer...

**Comment by TroubleMakerBen** [comment] 2017-11-08 19:11
Hey @callanh,

**I was referring to support for handled exceptions. There is no ETA for line numbers in stack traces.**
Sorry for not being explicit about the ETAs.

Best,
Benjamin

**Comment by logikonline** [comment] 2017-11-08 19:22
@callanh  Line numbers would only be included in the exception in debug mode.

@TroubleMakerBen it would great to be able to call the method to pass an exception from the PCL.  If we have to create a Dependency to pass it in the specific platform (iOS, Android) - this is fine but I would like the ability to pass a System.Exception manually.

**Comment by scastria** [comment] 2018-01-24 16:23
What is the status on this?  And when migrating away from Insights, should I go to hockeyapp or mobile center?  It would seem that mobile center is built on top of hockeyapp so migrating straight to hockeyapp would give me more functionality??

**Comment by ChaseFlorell** [comment] 2018-01-24 16:46
This is a really STUPID problem to have folks.
We've now been informed that Insights is definitely being retired THIS YEAR, and yet the feature that many of us have built into our apps is going away. WT actual F?

You might be saying "use App Center instead", but...

1) this feature isn't fully baked in App Center either
2) enterprise is slow to change, so for all the corps that switched from Insights to HockeyApp based on the original memo are going to be slow to adopt yet another platform (App Center).

**Comment by TroubleMakerBen** [comment] 2018-01-24 19:21
Hey folks,

Most of the discussion around this has happened over on the repo of the App Center SDK [here](
https://github.com/Microsoft/AppCenter-SDK-DotNet/issues/140).

I completely agree that the situation isn't ideal and we all hear you.

Here's what's gonna happen (the TL;DR of the issue in the issue above):
* Support for handled exceptions won't be coming to HockeyApp. 
* We are actively working on support for handled errors/exceptions in App Center and this will ship very soon, I can't give you an exact ETA but this is worked on with the highest priority as I write this. 
* If you are interested in using a preview of handled exceptions in App Center, please let us know and we'll give you access as soon as we have a it.

Best,
Benjamin

**Comment by logikonline** [comment] 2018-01-24 22:19
I think we all struggle because to add a simple method to record the exception is so basic that time it took to read this thread - it could have been completed and would fall inline with every developer's normal error handling.

instead we are given yet another promise of an upcoming support.  

I wrote around HockeyApp with my own as I am sure every other dev on this thread has had too or they are simply ignoring the errors with blanket try/catch.  If this is out before Q3 - I will be shocked.

**Comment by TroubleMakerBen** [comment] 2018-01-24 23:56
@logikonline 
I understand that you are frustrated and also get the sarcasm about the topic. Let's just say that it's not so simple as to just adding an API that takes one string and hack something together before lunch. That said, you are right that this is our problem to solve and we shouldn't make it your problem to find workarounds.

Let's be clear about 
`If this is out before Q3 - I will be shocked.`

This is gonna ship this spring.

Best,
Benjamin

**Comment by scastria** [comment] 2018-01-25 03:03
Can you be more specific?  Spring may not be the same as March 31. If Insights is shutting down on March 31, its equivalent functionality should be available BEFORE that time. Can you commit that handled exceptions will be available BEFORE Insights shuts down?

**Comment by logikonline** [comment] 2018-01-25 08:35
@TroubleMakerBen You are correct and perhaps I could've been a tad more polite about it but most of us on this thread were literally asking for a method to be exposed that must already be written to merely submit an exception which the solution does presently.  I even noted that you could require us to write a custom renderer to access it on the platform specific instead of a small wrapper for Xamarin Forms.

This is not asking for some complex rewrite - just an exposed method. 

I look forward to evaluating the new solution in Spring.

**Comment by TroubleMakerBen** [comment] 2018-01-25 20:10
@scastria I can't provide you with an exact ETA but we are committed to add support for handled exceptions in App Center for Xamarin Insights customers before Xamarin Insights is shut down.

**Comment by scastria** [comment] 2018-01-25 21:50
@troublemakerben good enough for me. thanks.

**Comment by AzimAnsari** [comment] 2018-02-21 13:00
Guyzz, Please let me know if [https://support.hockeyapp.net/kb/api/api-crashes#post-custom-crashes](https://support.hockeyapp.net/kb/api/api-crashes#post-custom-crashes) is anyhow related to what we are waiting for, for more that one year.
Is this a very secret API that Hockey Dev team is trying to hide from cruel developers like me?

**Comment by TroubleMakerBen** [comment] 2018-02-21 17:06
Hi @AzimAnsari,
Short answer: No, we are not hiding this from you. This API is intended for customers who want to submit custom crash reports for native crashes.

We're very very close to shipping support for handled exception support in [AppCenter](https://appcenter.ms) (you have no idea how close) and will give everyone a Preview-Access as soon as we can. Watch for our announcements.
Support for Handled Exceptions won't come to HockeyApp but to App Center.

**Comment by EmilAlipiev** [comment] 2018-02-23 11:40
Looking forward to it before we disconnect Xamarin insights.
Also it would be lovely to send this exceptions on real time, instantly like xamarin insights does, not when app is opened next time.  Because if you implement this that it would be quite disappointing. Reason for that is if a new user comes to your app and has an handled exception which cause a major function to not work or some UI element to be not displayed. Many users will just exit app and uninstall your app and there wont next app load and you will never get to know about this exception unless you catch yourself. 
I wrote this annotation because I read earlier somewhere that team is planing something like that if I remember correctly.

**Comment by TroubleMakerBen** [comment] 2018-02-23 21:48
Hey @EmilAlipiev,

Handled exceptions in App Center will be send almost in real time, just like other events, no need to close and reopen the app.

Best,
Benjamin

**Comment by blparr** [comment] 2018-03-01 01:32
Hello everyone, I have very good news for everyone in this thread!
**Handled Errors in Xamarin are now available for preview in App Center!**

If you are interested in getting early access to this feature, please contact us via our support system (blue button on the right in the App portal), and we will enable the feature for your account.
In this preview release, we are looking for your feedback and identification of any potential issues, so please talk to us and let us know what you think!

Thanks all for your patience on getting this feature ready!
Have an amazing rest of your day.

Blanca

**Comment by valdetero** [comment] 2018-03-01 03:14
@blparr this is great! I assume we’ll need to download an updated nuget too?

**Comment by vhugogarcia** [comment] 2018-03-01 14:55
Hello @blparr, I'm so happy to hear these fantastic news! I'm really really glad you could add this desired feature.

I would like to join the preview, so I can also help with the testing. However, I don't see the blue button on the app portal, I clicked support from my user menu and there is no blue button or way to request the access.

Is there another way to request it? or am I missing a step?

Thanks again for your hard work at this!

Regards,
Victor

**Comment by EmilAlipiev** [comment] 2018-03-01 15:16
It works good, only it is a bit slower than xamarin insights. I tested side by side Insights shows the exception instantly, App center displays between 10-30mins later.  I guess that it is because it is in preview yet. Looking forward to have Xamarin UWP as well :)

**Comment by TroubleMakerBen** [comment] 2018-03-01 16:47
Hi folks,

to contact support, go to [support.hockeyapp.net](https://support.hockeyapp.net) and click on "open support"

<img width="988" alt="screen shot 2018-03-01 at 8 41 22 am" src="https://user-images.githubusercontent.com/10164200/36857250-e3587728-1d2c-11e8-8b6c-a5c08f23f803.png">

@valdetero 
You need to use the AppCenter SDK instead of the HockeyApp SDK. If you need help with the migration, just get in touch through support.

Cheers,
Benjamin.

**Comment by valdetero** [comment] 2018-03-01 16:51
@TroubleMakerBen I am already using the AppCenter SDK -> Microsoft.AppCenter.Crashes v1.1.0. What method do I call for the handled exceptions?
Also, the screenshot above is from https://rink.hockeyapp.net/help and not support.hockeyapp.net. I did that from App Center and haven't received a reply.

**Comment by blparr** [comment] 2018-03-01 20:04
@valdetero Hi there, did you receive a response on the App Center support system yet (blue button on the bottom right of the app center portal)? I'd like to make sure we don't miss your conversation!

Once you get access to the feature (if you don't have it yet), you need to go to Errors section under Diagnostics. You can learn more about this feature here: https://docs.microsoft.com/en-us/appcenter/errors/

**Comment by valdetero** [comment] 2018-03-01 20:17
@blparr Yes! thank you. I jumped over to appcenter github and found the corresponding issue and it told me what I needed to do to implement it in my app.

**Comment by tonywamba** [comment] 2018-04-11 12:52
@blparr I was able to try the _Handled Error_ features but unfortunately, the stack trace of the Exception is not sent to App Center. I was only able to see the Message. I understand the feature is still in Preview but is this intended or the full stack trace will be available soon?
![unbenannt](https://user-images.githubusercontent.com/4300794/38617652-dee1022e-3d97-11e8-9121-b01671146584.PNG)

**Comment by blparr** [comment] 2018-04-11 17:05
@tonywamba Hello, this is a known issue and we plan to work on improving it. Thanks for reporting this!

**Closed** 2020-02-19 14:06 UTC
Labels: feature-request, not planned
