### ISSUE TITLE
Crash Report on Xamarin 5.2.0 iOS

### ISSUE THREAD

**Issue by czuvich** [bitstadium/HockeySDK-Xamarin#138] opened 2019-06-27 20:05 UTC
Xamarin Forms iOS App
Xamarin Hockey 5.2.0 iOS

I'm seeing the following exception being logged via hockey on our Xamarin Forms iOS app.

```
Last Exception Backtrace:
0   CoreFoundation                       0x00000001b917e3a8 __exceptionPreprocess + 232
1   libobjc.A.dylib                      0x00000001b8383d00 objc_exception_throw + 56
2   CoreFoundation                       0x00000001b90976c8 -[NSException raise] + 12
3   MobileTrack.iOS                      0x000000010267e098 wrapper_managed_to_native_Xamarin_ObjCRuntime_Messaging_void_objc_msgSend_intptr_intptr (<unknown>:1)
4   MobileTrack.iOS                      0x0000000102681354 HockeySDK_iOSBindings_HockeyApp_iOS_BITHockeyManager_ConvertToNsExceptionAndAbort_object + 260
```
Here's the exception trace
```
Application Specific Information:
*** Terminating app due to uncaught exception 'System.ArgumentOutOfRangeException', reason: 'System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.'

Xamarin Exception Stack:
Parameter name: index
  at System.Collections.Generic.List`1[T].get_Item (System.Int32 index) <0x100d64f00 + 0x0004b> in <4db5e915761a454b810fa3913e31be34#17161b22946fba777b3431f3b3c47e37>:0 
  at Foundation.NSNotificationCenter.RemoveObserver (Foundation.NSObject observer) <0x1017f4e20 + 0x00053> in <497181d9d26447828f8574819afeb3d5#17161b22946fba777b3431f3b3c47e37>:0 
  at System.Net.Http.NSUrlSessionHandler.RemoveInflightData (Foundation.NSUrlSessionTask task, System.Boolean cancel) <0x10185a7dc + 0x0011f> in <0da8ced3e38d42039920e99e08ca9321#17161b22946fba777b3431f3b3c47e37>:0 
  at System.Net.Http.NSUrlSessionHandler+NSUrlSessionHandlerDelegate.DidCompleteWithError (Foundation.NSUrlSession session, Foundation.NSUrlSessionTask task, Foundation.NSError error) <0x10185aec4 + 0x000bf> in <0da8ced3e38d42039920e99e08ca9321#17161b22946fba777b3431f3b3c47e37>:0
```

Xamarin has confirmed it's a bug on their side (https://github.com/xamarin/xamarin-macios/issues/6387).  I was wondering though if there was something we could do on Hockey's side so that reporting the exception doesn't cause another exception.

**Comment by russelarms** [comment] 2019-06-28 07:46
I believe it is a part of a crash caused by a code not related to Hockey SDK. Hockey just behaves normally. So it is better to wait for it to be fixed on the xamarin side.

**Comment by czuvich** [comment] 2019-06-28 14:31
I understand the problem is not in Hockey.  Is there some workaround for it though?  The problem is that Hockey is trying to report the exception, and it looks like Hockey is crashing the app doing it.  Ideally, it would not crash the app reporting an exception.  I'm fairly certain you'll see more of these popping up until Xamarin.iOS resolves the issue.

**Comment by MatkovIvan** [comment] 2019-07-01 08:38
Hey @czuvich,

HockeyApp reports it when the app has already crashed, the logs can be a little misleading, but it's just a way to report them. If it doesn't crash the app itself, then there is no HockeyApp report at all. So the HockeyApp doesn't change this behavior - it will crash with crash reporter tool or not.

I'm closing this issue, feel free to reopen if you still have any questions.

Thanks,
Ivan

**Closed as completed by MatkovIvan** 2019-07-01 08:38 UTC
