### ISSUE TITLE
Xamarin Forms Android Release Build fails with 5.0.0

### ISSUE THREAD

**Issue by Vandersteen** [bitstadium/HockeySDK-Xamarin#97] opened 2017-09-29 12:39 UTC
Hello,

today I've updated Xamarin Forms to 2.4.0 and I could still build our project in release mode (With HockeyAppSDK 4.1.5)

Updating to HockeyAppSDK 5.0.0 our app no longer builds in release mode (it does in debug mode though) with following warnings and error:

```
PROGUARD : warning : net.hockeyapp.android.utils.PermissionsUtil: can't find referenced method 'boolean canRequestPackageInstalls()' in library class android.content.pm.PackageManager
PROGUARD : warning : net.hockeyapp.android.utils.Util: can't find referenced method 'Notification$Builder(android.content.Context,java.lang.String)' in library class android.app.Notification$Builder
PROGUARD : warning : net.hockeyapp.android.utils.Util: can't find referenced class android.app.NotificationChannel
PROGUARD : warning : net.hockeyapp.android.utils.Util: can't find referenced class android.app.NotificationChannel
PROGUARD : warning : net.hockeyapp.android.utils.Util: can't find referenced method 'void createNotificationChannel(android.app.NotificationChannel)' in library class android.app.NotificationManager
PROGUARD : warning : net.hockeyapp.android.utils.Util: can't find referenced class android.app.NotificationChannel
PROGUARD : warning : there were 3 unresolved references to classes or interfaces.
PROGUARD : warning : there were 3 unresolved references to library class members.
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1929,3): error MSB6006: "java" exited with code 1.
```

**Visual Studio**

```
Visual Studio Community 2017 for Mac
Version 7.1.5 (build 2)
Installation UUID: xxx
Runtime:
	Mono 5.2.0.224 (d15-3/14f2c81) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 502000224

NuGet
Version: 4.3.0.2418

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/1.0.3/Sdks
SDK Version: 1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
'/Applications/Xamarin Profiler.app' not found

Apple Developer Tools
Xcode 9.0 (13247)
Build 9A235

Xamarin.Mac
Version: 3.6.3.3 (Visual Studio Community)

Xamarin.Android
Version: 7.4.5.1 (Visual Studio Community)
Android SDK: /Users/rein/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 25.0.1
SDK Build Tools Version: 25.0.1

Java SDK: /usr
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Xamarin Inspector
Version: 1.3.1
Hash: cbc48dd
Branch: 1.3-release
Build date: Thu, 21 Sep 2017 19:52:53 GMT
Client compatibility: 1

Xamarin.iOS
Version: 11.0.0.0 (Visual Studio Community)
Hash: 152b654a
Branch: xcode9
Build date: 2017-09-15 02:25:56-0400

Build Information
Release ID: 701050002
Git revision: 7afedcaef8e7542e70e3cf8f9bdb26938b8c0876
Build date: 2017-09-15 08:39:58-04
Xamarin addins: 3262aadf811a18c12eac6742532d052b0139a808
Build lane: monodevelop-lion-d15-3-xcode9

Operating System
Mac OS X 10.12.6
Darwin 16.7.0 Darwin Kernel Version 16.7.0
    Thu Jun 15 17:36:27 PDT 2017
```

**.csproj configuration**

```
  <Import Project="..\packages\Xamarin.Forms.2.4.0.280\build\netstandard1.0\Xamarin.Forms.props" Condition="Exists('..\packages\Xamarin.Forms.2.4.0.280\build\netstandard1.0\Xamarin.Forms.props')" />
  <Import Project="..\packages\Xamarin.Build.Download.0.4.7\build\Xamarin.Build.Download.props" Condition="Exists('..\packages\Xamarin.Build.Download.0.4.7\build\Xamarin.Build.Download.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectTypeGuids></ProjectTypeGuids>
    <ProjectGuid></ProjectGuid>
    <OutputType>Library</OutputType>
    <RootNamespace>B2B.Droid</RootNamespace>
    <MonoAndroidAssetsPrefix>Assets</MonoAndroidAssetsPrefix>
    <MonoAndroidResourcePrefix>Resources</MonoAndroidResourcePrefix>
    <AndroidManifest>Properties\AndroidManifest.xml</AndroidManifest>
    <AndroidResgenClass>Resource</AndroidResgenClass>
    <AndroidResgenFile>Resources\Resource.designer.cs</AndroidResgenFile>
    <AndroidApplication>True</AndroidApplication>
    <AndroidUseLatestPlatformSdk>true</AndroidUseLatestPlatformSdk>
    <AssemblyName>B2B.Droid</AssemblyName>
    <TargetFrameworkVersion>v7.1</TargetFrameworkVersion>
    <ReleaseVersion>1.2</ReleaseVersion>
    <AndroidTlsProvider></AndroidTlsProvider>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug</OutputPath>
    <DefineConstants>DEBUG;</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <AndroidLinkMode>None</AndroidLinkMode>
    <ConsolePause>false</ConsolePause>
    <RunCodeAnalysis>false</RunCodeAnalysis>
    <AndroidKeyStore></AndroidKeyStore>
    <AndroidTlsProvider>btls</AndroidTlsProvider>
    <AndroidEnableSGenConcurrent>true</AndroidEnableSGenConcurrent>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugSymbols>false</DebugSymbols>
    <DebugType></DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release</OutputPath>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <AndroidUseSharedRuntime>false</AndroidUseSharedRuntime>
    <ConsolePause>false</ConsolePause>
    <RunCodeAnalysis>true</RunCodeAnalysis>
    <AndroidSupportedAbis>armeabi-v7a;x86;armeabi</AndroidSupportedAbis>
    <AndroidLinkMode>Full</AndroidLinkMode>
    <EnableProguard>true</EnableProguard>
    <AndroidEnableSGenConcurrent>true</AndroidEnableSGenConcurrent>
    <AndroidTlsProvider>btls</AndroidTlsProvider>
    <AndroidLinkSkip>Xamarin.Android.Support.v7.AppCompat;Xamarin.Android.Support.v4</AndroidLinkSkip>
    <AotAssemblies>True</AotAssemblies>
    <EnableLLVM>True</EnableLLVM>
    <AndroidAotAdditionalArguments>no-write-symbols,nodebug</AndroidAotAdditionalArguments>
    <EmbedAssembliesIntoApk>True</EmbedAssembliesIntoApk>
  </PropertyGroup>
```

Downgrading to 4.1.5 'solves' the issue

**Comment by Vandersteen** [comment] 2017-09-29 12:46
I have tried the following things without success:

* Enabling Multidex
* Setting Java Heap to 2G
* Cleaning multiple times
* Updating Android SDK's and build tools
* Manually deleting bin folder
* Rebooting after all this

**Comment by MatkovIvan** [comment] 2017-10-02 06:28
Hi @Vandersteen

Looks like https://github.com/bitstadium/HockeySDK-Android/issues/298#issuecomment-328524812
You need to update Android SDK (or double check this) or add ignore flag to ProGuard.

**Comment by TroubleMakerBen** [comment] 2017-10-11 18:32
Hey @Vandersteen 
Have you been able to resolve the issue? I'll close the issue end of the week if I don't hear back from you. 
Benny

PS: you can always re-open this, of course. =)

**Comment by Vandersteen** [comment] 2017-10-11 18:34
Hello, I haven't been able to try it out.
I should have the time tomorrow and the day after. I'll report my findings asap.

Thanks for the reminder

**Comment by TroubleMakerBen** [comment] 2017-10-12 19:32
@Vandersteen no worries, I'll leave this open for some more time. =)

**Comment by Vandersteen** [comment] 2017-10-14 19:43
Unfortunately, even after updating, I still get the same error when building Release versions.

```
PROGUARD : warning : net.hockeyapp.android.utils.PermissionsUtil: can't find referenced method 'boolean canRequestPackageInstalls()' in library class android.content.pm.PackageManager
PROGUARD : warning : net.hockeyapp.android.utils.Util: can't find referenced method 'Notification$Builder(android.content.Context,java.lang.String)' in library class android.app.Notification$Builder
PROGUARD : warning : net.hockeyapp.android.utils.Util: can't find referenced class android.app.NotificationChannel
PROGUARD : warning : net.hockeyapp.android.utils.Util: can't find referenced class android.app.NotificationChannel
PROGUARD : warning : net.hockeyapp.android.utils.Util: can't find referenced method 'void createNotificationChannel(android.app.NotificationChannel)' in library class android.app.NotificationManager
PROGUARD : warning : net.hockeyapp.android.utils.Util: can't find referenced class android.app.NotificationChannel
PROGUARD : warning : there were 3 unresolved references to classes or interfaces.
PROGUARD : warning : there were 3 unresolved references to library class members.
```

**Comment by Vandersteen** [comment] 2017-10-14 19:55
Disabling Proguard solves it though.

**Comment by Vandersteen** [comment] 2017-10-14 20:02
I was able to make it build by using the following:

Heap Size: 2G
Proguard: Active
Multidex: Active

Added the following to proguard-android.txt

```
-keep public class net.hockeyapp.android.utils.* { public *; }
-dontwarn net.hockeyapp.android.utils.**
```

**Comment by MatkovIvan** [comment] 2017-10-18 12:27
Hi @Vandersteen 

I'm glad that you solved the problem, but I think it isn't the root cause.
I've rechecked this case and couldn't reproduce it with the updated version of Android SDK.

Based on your ProGuard log, it cannot find **classes from standard android library** added in **8.0 (API level 26)**. Also in Visual studio log posted in your first post, this API level doesn't listen in `Supported Android versions`. So, I'm of the opinion that for some reason a new API cannot be found in the build process in your environment.

Thanks,
Ivan

**Comment by Vandersteen** [comment] 2017-10-18 13:04
Hey,

Thanks for the response, we do target API 25 (7.1) and that is also the last installed version on our build system. I will give it a shot and install the API 26 SDK's as well, I'll report my findings here.

**Comment by TroubleMakerBen** [comment] 2017-10-25 01:09
Hey @Vandersteen,

any chance you tried this using the Android 8 SDK/API level 26?

Benjamin

**Comment by Vandersteen** [comment] 2017-10-25 08:51
I will today -

**Comment by Vandersteen** [comment] 2017-10-25 09:39
I just did install the 8.0 SDK's - removed my edits from the proguard.txt, removed the bin and obj directory - Clean All + Rebuild and the errors did go away.

Thank you for taking the time and spotting the real issue.

**Comment by TroubleMakerBen** [comment] 2017-10-25 16:10
Hey Reinald,

I'm glad you were able to resolve the issues.
Thx for using HockeyApp!
Best,
Benjamin

**Comment by Vandersteen** [comment] 2017-10-26 12:24
FYI: This issue re-occured after a reboot.
Seems like the proguard config was still cached or something.

I ended up re-installing the SDK-build tools and and Platforms. (up to 8.0 / 26)
The issue still persisted until I changed the target platform of our app to 8.0, at that point the error did disappear.

**Closed** 2018-01-22 18:13 UTC
